package com.company.pages;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.WindowConstants;

import com.company.App;
import com.company.utilities.ReadWrite;

/**
 * The main container used to hold all of the program's data.
 */
public class HealthcareApp extends JFrame implements WindowListener {
    private JPanel login;
    private JPanel program;

    /**
     * Initializes the main frame as the main container and adds the login panel. The frame's size, location, and some other settings are predetermined.
     */
    public HealthcareApp() {
        super("Healthcare Management Interface for Specialists");

        login = new Login();
        this.add(login);  // Default

        this.addWindowListener(this);
        this.setSize(1024, 576);
        this.setLocationRelativeTo(null);  // Center of the screen when opened
        this.setResizable(false);
        this.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * Method to swap the login page with the program page. Assumes that the login page is the current page.
     */
    public void LoggedIn() {
        program = new Program();  // Avoid NullPointerException
        this.remove(login);
        this.add(program);
        this.revalidate();
        this.repaint();
    }

    /**
     * Method to swap the program page with the login page. Assumes that the program page is the current page.
     */
    public void LogOut() {
        this.remove(program);
        this.add(login);
        this.revalidate();
        this.repaint();
        // Remember to reset some values (like current user)
    }

    /**
     * When the app closes, database information generated by the program gets written the their respective <code>.json</code> files.
     */
    @Override
    public void windowClosing(WindowEvent e) {
        ReadWrite.writeFile(App.dsm.packPatients(), "patients.json");
        ReadWrite.writeFile(App.dsm.packAppointments(), "appointments.json");
        ReadWrite.writeFile(App.dsm.packOtherdata(), "otherdata.json");
    }

    @Override
    public void windowOpened(WindowEvent e) {}

    @Override
    public void windowClosed(WindowEvent e) {}

    @Override
    public void windowIconified(WindowEvent e) {}

    @Override
    public void windowDeiconified(WindowEvent e) {}

    @Override
    public void windowActivated(WindowEvent e) {}

    @Override
    public void windowDeactivated(WindowEvent e) {}
}
